### PR TITLE
Add 5 new addons

### PR DESCRIPTION
**Pull request by jlvcm**
Just added some compatibility with PimpMyStream for my addons

### CODE REVIEW

**Comment by sungshon** [comment]
Oh wow, thanks.

A few mentions though, you will need to create a github release for each repository / addon (you don't need to attach any files, just set a unique tag version for them)

PimpMyStremio uses the releases to download to the users, and every time you make changes and want to update to the users, simply make a new release.

Another thing is that it might be a good idea to use the PimpMyStremio internal proxy for iptvOrg, it makes more streams work usually because it does handles header cache requirements.

To use the proxy, just do:
```
const { proxy } = require('internal')
```

And then on this line:
https://github.com/jlvcm/stremio-ptiptv/blob/master/addon.js#L104

Change it to:
```
			url: proxy.addProxy(stream)
```

I think this might increase stream success.

I'll test your addons tomorrow to make sure they work and merge if they do.

**Comment by sungshon** [comment]
Oh, one more mention, I think YTS only has movies, it does not have series, so it should be changed to:
```
		"types": ["Movies"],
```
in the Pull Request.

**Comment by jlvcm** [comment]
changed IPTV, fixed the YTS typo and added releases, thanks @sungshon, let em know if something does not work or needs fixing

**Comment by sungshon** [comment]
I've had a chance to test your addons, the only one that does not is YTS, which gives an error because the `node-cache` module is missing, PimpMyStremio addons are limited to only these modules: https://github.com/sungshon/PimpMyStremio/blob/master/docs/modules-whitelist.md

The other 4 addons all work fine. If you want to test the addons yourself, there are 2 ways of doing this:
- sideload an addon: https://github.com/sungshon/PimpMyStremio/blob/master/docs/README.md#testing-add-ons
- (alternatively) in PimpMyStremio's settings, you can change the "Remote Add-ons List URL" to the one in your PR (which is: https://raw.githubusercontent.com/jlvcm/PimpMyStremio/patch-3/src/addonsList.json ) and restart PimpMyStremio, this will make the app pull your own addon list over the default one, and you can change it back to the default one (so it auto-updates itself in the future, the default one is: https://raw.githubusercontent.com/sungshon/PimpMyStremio/master/src/addonsList.json )

I just used the second method, although I can guarantee that if you use only the default modules, it will certainly just work, just mentioned the addon testing methods for future reference if you need them.

**Comment by sungshon** [comment]
Oh, don't forget to make another release for YTS after you made the changes. :)

**Comment by pakamoon** [comment]
I've made a PR to YTS to fix compatibility to PimpMyStremio, as @sungshon mentioned, you should also make a new release for YTS after merging that PR.

**Comment by jlvcm** [comment]
done, thanks @sungshon and @pakamoon

**Comment by sungshon** [comment]
yup, works fine now, merging

**Pull request merged**
