### PR TITLE
Add "Awesome Everything" add-on

### PR DESCRIPTION
**Pull request by PurposeUnknown42**

### CODE REVIEW

**Comment by sungshon** [comment]
thank you!

**Comment by sungshon** [comment]
can you please make a release too? it's needed for the add-on update/download to work

**Comment by PurposeUnknown42** [comment]
srry, forgot to make the release

it's done now

**Comment by sleeyax** [comment]
This add-on is genious. Just wanted to say great work @PurposeUnknown42 :P

**Pull request merged**
